export function createScheduleGridController({ root = document, grid, days, times, defaults, timeToMinutes, getBlockDurations, getBlockDuration, durationsStorageKey, queueBackup }) {
  const appendEditable = (element, id, label) => { element.contentEditable = "true"; element.dataset.editable = id; element.setAttribute("role", "textbox"); element.setAttribute("aria-label", label); return element; };
  const build = () => {
    const corner = document.createElement("div"); corner.className = "schedule-corner"; corner.style.gridColumn = "1"; corner.style.gridRow = "1"; corner.textContent = "Horário"; grid.append(corner);
    days.forEach((day, dayIndex) => { const heading = document.createElement("div"); heading.className = "day-heading day-card-head"; heading.dataset.day = day.key; heading.style.gridColumn = String(dayIndex + 2); heading.style.gridRow = "1"; const name = document.createElement("span"); name.className = "day-heading-name"; name.textContent = day.label; const progress = document.createElement("div"); progress.className = "day-progress"; progress.dataset.dayProgress = day.key; progress.setAttribute("role", "progressbar"); progress.setAttribute("aria-label", `Progresso de ${day.label}`); const fill = document.createElement("span"); fill.className = "day-progress-fill"; progress.append(fill); heading.append(name, progress); grid.append(heading); });
    times.forEach((time, timeIndex) => {
      const timeCell = document.createElement("div"); timeCell.className = "time-cell"; timeCell.dataset.time = time; timeCell.style.gridColumn = "1"; timeCell.style.gridRow = String(timeIndex + 2);
      const timeBadge = document.createElement("span"); timeBadge.className = "time-badge"; timeBadge.textContent = time;
      const energy = timeToMinutes(time) < 720 ? 100 : timeToMinutes(time) < 1080 ? 60 : 20;
      const energyMark = document.createElement("i"); energyMark.className = "energy-mark"; energyMark.dataset.energy = String(energy); energyMark.title = `Energia cognitiva estimada: ${energy}%`; timeCell.append(timeBadge, energyMark); grid.append(timeCell);
      days.forEach((day, dayIndex) => {
        const id = `${day.key}-${time}`; const [text = "", type = ""] = defaults[id] || []; const span = 1;
        const task = document.createElement("div"); task.className = `schedule-slot ${type ? `slot--${type}` : ""}`; task.dataset.baseClass = task.className; task.dataset.day = day.key; task.dataset.time = time; task.dataset.span = String(span); task.dataset.energy = String(energy); task.style.gridColumn = String(dayIndex + 2); task.style.gridRow = `${timeIndex + 2} / span ${span}`;
        const content = appendEditable(document.createElement("span"), `slot-${id}`, `${day.label}, ${time}`); content.className = "slot-content"; content.textContent = text; task.append(content);
        const duration = document.createElement("span"); duration.className = "slot-duration"; duration.contentEditable = "true"; duration.dataset.duration = id; duration.setAttribute("role", "textbox"); duration.setAttribute("aria-label", `Duração estimada de ${day.label}, ${time}`); const configuredDuration = Number(getBlockDurations()[id]); duration.textContent = `${Number.isFinite(configuredDuration) && configuredDuration > 0 ? configuredDuration : span * 60}m`; task.append(duration);
        const status = type === "work" && day.key === "mon" && time === "13:00" ? "Trabalho" : id === "wed-22:00" ? "Recuperação" : "";
        if (status && text) { const badge = document.createElement("span"); badge.className = `slot-status slot-status--${type}`; badge.textContent = status; task.append(badge); }
        const supportsMark = type === "work" || text.includes("Ritual 5S");
        if (supportsMark) { const mark = document.createElement("label"); mark.className = "slot-check"; const input = document.createElement("input"); input.type = "checkbox"; input.dataset.slotCheck = id; input.setAttribute("aria-label", `Concluir ${text || "bloco"} em ${day.label}`); mark.append(input); task.append(mark); }
        grid.append(task);
      });
    });
  };
  const entries = (dayKey) => [...root.querySelectorAll(`.schedule-slot[data-day="${dayKey}"]:not(.is-continuation)`)].map((slot) => { const time = slot.dataset.time; const content = slot.querySelector(".slot-content"); return { slot, time, start: timeToMinutes(time), text: content?.innerText.trim() || "", duration: getBlockDuration(`${dayKey}-${time}`), base: slot.dataset.baseClass || "" }; }).filter((entry) => entry.text).sort((first, second) => first.start - second.start);
  const contentForTime = (dayKey, time) => { const direct = root.querySelector(`[data-editable="slot-${dayKey}-${time}"]`); if (direct && !direct.closest(".schedule-slot")?.classList.contains("is-continuation")) return direct; const target = timeToMinutes(time); const entry = entries(dayKey).find((item) => target >= item.start && target < item.start + item.duration); return entry?.slot.querySelector(".slot-content") || direct; };
  const refreshContinuousBlocks = () => {
    const durations = getBlockDurations(); let durationsChanged = false;
    root.querySelectorAll(".schedule-slot").forEach((slot) => { slot.className = slot.dataset.baseClass || "schedule-slot"; slot.dataset.span = "1"; slot.style.gridRow = String(times.indexOf(slot.dataset.time) + 2); slot.classList.toggle("is-marked", Boolean(slot.querySelector("[data-slot-check]")?.checked)); });
    days.forEach((day) => { let consumedUntil = 0; times.forEach((time, timeIndex) => { if (timeIndex < consumedUntil) return; const startSlot = root.querySelector(`[data-editable="slot-${day.key}-${time}"]`)?.closest(".schedule-slot"); const text = startSlot?.querySelector(".slot-content")?.innerText.trim() || ""; if (!startSlot || !startSlot.dataset.baseClass.includes("slot--work") || !text) return; const matchingSlots = [startSlot]; for (let index = timeIndex + 1; index < times.length; index += 1) { const nextSlot = root.querySelector(`[data-editable="slot-${day.key}-${times[index]}"]`)?.closest(".schedule-slot"); const nextText = nextSlot?.querySelector(".slot-content")?.innerText.trim() || ""; if (!nextSlot || !nextSlot.dataset.baseClass.includes("slot--work") || nextText !== text) break; matchingSlots.push(nextSlot); } if (matchingSlots.length < 2) return; const storedDuration = Number(durations[`${day.key}-${time}`]); const span = storedDuration > 60 ? Math.min(matchingSlots.length, Math.max(1, Math.ceil(storedDuration / 60))) : matchingSlots.length; const totalDuration = span * 60; consumedUntil = timeIndex + span; if (durations[`${day.key}-${time}`] !== totalDuration) { durations[`${day.key}-${time}`] = totalDuration; durationsChanged = true; } startSlot.classList.add("schedule-slot--continuous"); startSlot.dataset.span = String(span); startSlot.style.gridRow = `${timeIndex + 2} / span ${span}`; const durationField = startSlot.querySelector(`[data-duration="${day.key}-${time}"]`); if (durationField) durationField.textContent = `${totalDuration}m`; matchingSlots.slice(1, span).forEach((slot) => { slot.classList.add("is-continuation"); slot.dataset.continuationOf = `${day.key}-${time}`; }); }); });
    if (durationsChanged) { localStorage.setItem(durationsStorageKey, JSON.stringify(durations)); queueBackup(); }
  };
  return { build, getScheduleEntries: entries, slotContentForTime: contentForTime, refreshContinuousBlocks };
}
